### ISSUE TITLE
Mettre en place une messagerie interne

### ISSUE THREAD

**Issue by Lightuky** [Tais-Juhel/Immotep#16]
**Description**

- En tant que
- Je veux 
- Afin de 

**Critère d'acceptation**

- Elements de la fonctionnalité:
- [ ] élément 1
- [ ] élément 2
- [ ] élément 3
- [ ] ...

- Visuel (maquette ou inspiration) :

**Comment by Sukenpoud** [comment]
Pas trop l'temps

**Comment by Sukenpoud** [comment]
Pas l'temps déso
